### ISSUE TITLE
WHERE ARE BLOG POST?!

### ISSUE THREAD

**Issue by felixangell** [vnev/blank#2]
I WAS ON MY WAY TO WORK AND IWAS GOING TO LEARN PROGRAMB UT U KNO HAVE LBLOG PLOSTS!!!

**Comment by felixangell** [comment]
# where they go!?!

**Comment by felixangell** [comment]
- where
- where!!!

**Comment by ghost** [comment]
@felixangell Hypocrite.

**Comment by vnev** [comment]
ey bous pls

![](http://i.giphy.com/uSn5nkznvTLOg.gif)

**Comment by felixangell** [comment]
@0xc6 touche ;)
